### ISSUE TITLE
Version-name conflict

### ISSUE THREAD

**Issue by engel-exxeta** [talon-one/maven-artefacts#3]
Trying to update talon-one-client to current version causes an

`Unresolved dependency: 'one.talon:talon-one-client:jar:4.5.0-rc'`

I assume it is a conflict between naming the version-folder (4.5.0-**_rc_**) and the artefacts within (4.5.0).

**Comment by altJake** [comment]
Hello @engel-exxeta,

Thank you very much for the issue and pointing it out. We are working on a quick fix for it already!
